import type { Metadata } from "next";
import BlogHeader from "@/components/BlogHeader";
import ClientRootConatiner from "@/components/ClientRootContainer";
import BlogFooter from "@/components/BlogFooter";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body className="font-Pretendard bg-light-background dark:bg-dark-background">
        <div className="max-w-3xl px-6 mx-auto lg:max-w-6xl lg:px-8">
          <BlogHeader />
          <ClientRootConatiner>
            {children}
          </ClientRootConatiner>
        </div>
        <BlogFooter />
      </body>
    </html>
  );
}
